name = "PlutoDependencyExplorer"
uuid = "72656b73-756c-7461-726b-72656b6b696b"
license = "MIT"
authors = ["Paul Berg <paul@plutojl.org>", "Fons van der Plas <fons@plutojl.org>"]
version = "1.0.3"

[deps]
ExpressionExplorer = "21656369-7473-754a-2065-74616d696c43"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
ExpressionExplorer = "0.6, 1"
InteractiveUtils = "1"
Markdown = "1"
julia = "1.6"
